### ISSUE TITLE
CentOS identified as Ubuntu on Charmhub

### ISSUE THREAD

**Issue by heitorPB** [canonical-web-and-design/charmhub.io#1073]
Charmhub shows CentOS 7 as Ubuntu 7:

![slurmd](https://user-images.githubusercontent.com/13461702/125325476-5c773000-e317-11eb-801f-9b5085b8f460.png)

The [slurmd](https://charmhub.io/slurmd?channel=edge) charm has the following [`charmcraft.yaml`](https://github.com/omnivector-solutions/slurm-charms/blob/master/charm-slurmd/charmcraft.yaml):

```yaml
type: charm
bases:
  - build-on:
      - name: ubuntu
        channel: "20.04"
    run-on:
      - name: ubuntu
        channel: "20.04"
        architectures: [amd64]
      - name: centos
        channel: "7"
        architectures: [amd64]
```

The `run-on` section for CentOS is not correctly displayed on Charmhub
