### ISSUE TITLE
bundle icons are sourced incorrectly

### ISSUE THREAD

**Issue by sed-i** [canonical-web-and-design/charmhub.io#1096]
Bundle icons are pulled from the charms that make it. But instead of taking the charm name, charmhub currently uses the application name (which is an arbitrary string that charmhub should not rely on) to source the icons. Instead, charmhub should use the charm name to source the icons.

For example:

The [lma-light bundle](https://charmhub.io/lma-light) ([gh](https://github.com/canonical/lma-light-bundle)) lists the following in `bundle.yaml`:
```yaml
applications:
  alertmanager:
    charm: alertmanager-k8s
    # ...
  grafana:
    charm: grafana-k8s
    # ...
```

As a result, charmhub renders the following:
```html
  <div class="p-bundle-icons">
    <img src="/alertmanager/icon" alt="" />
    <img src="/grafana/icon" alt="" />
    
    <span class="p-bundle-icons__count u-text--muted">
      +1
    </span>
    
  </div>
```
The grafana icon show up, because ["grafana"](https://charmhub.io/grafana) happens to be an existing _different_ charm (compare to ["grafana-k8s"](https://charmhub.io/grafana-k8s)).
