### ISSUE TITLE
Platform UX messed up for multiple bases

### ISSUE THREAD

**Issue by wallyworld** [canonical-web-and-design/charmhub.io#1104]
See https://charmhub.io/juju-controller

I define several "run-on" bases in the charmcraft.yaml for the above charm. This messes up the "Platform" display.

```yaml
type: charm
bases:
    - build-on:
        - name: ubuntu
          channel: "20.04"
          architectures: ["amd64"]
      run-on:
        - name: ubuntu
          channel: "20.04"
          architectures:
              - amd64
              - aarch64
              - arm64
              - s390x
        - name: ubuntu
          channel: "18.04"
          architectures:
              - amd64
              - aarch64
              - arm64
              - s390x
        - name: ubuntu
          channel: "16.04"
          architectures:
              - amd64
              - aarch64
              - arm64
              - s390x
```
