### ISSUE TITLE
Resources do not show date

### ISSUE THREAD

**Issue by pedroleaoc** [canonical-web-and-design/charmhub.io#1311]
If you go to a charm's resources page (https://charmhub.io/finos-legend-studio-k8s/resources/studio-image), you can't see the revision number for a resource, but not the date information. 

![image](https://user-images.githubusercontent.com/5586487/161077565-11283603-a90a-4678-ba36-85add5ff5190.png)

You can get this information via the API:
```
curl -s https://api.charmhub.io/v2/charms/info/finos-legend-studio-k8s?fields=default-release.resources | jq '."default-release".resources[]'
```
```yaml
{
  "default-release": {
    "channel": {
      "track": "latest", 
      "base": {
        "architecture": "amd64", 
        "channel": "20.04", 
        "name": "ubuntu"
      }, 
      "name": "stable", 
      "released-at": "2021-10-21T11:52:36.322577+00:00", 
      "risk": "stable"
    }, 
    "resources": [
      {
        "revision": 2, 
        "description": "OCI image for the Engine (finos/legend-studio)", 
        "download": {
          "hash-sha3-384": "8bc9e01df406d9821521911162f14d4143515e70afd9c1691f7314f96ac0a932baed496d1785a08bd63a1644cbad8cb8", 
          "hash-sha-384": "acc2c6918bc8b7ac1ca96d510fd065de397e5b49fa094e0fd72e01f4e0ffcd2a1e74e92c20c497779854749f00c42b79", 
          "url": "https://api.charmhub.io/api/v1/resources/download/charm_ydBmjPqafc9RoYcAttbzpqZXvMliaXn3.studio-image_2", 
          "hash-sha-256": "3c4da4c35b5406faf994e775f5217fccb16973b7422a6109f9eb98a097cbb80f", 
          "hash-sha-512": "00b3784f30920e6cb9f5249afd4da4b126c6cf2224527299bbeae170124faade75d1a8023b8964d23593fedce4059df98982eaee763784e0e142336cbd373cbd", 
          "size": 503
        }, 
        "type": "oci-image", 
        "filename": "", 
        "created-at": "2021-09-24T17:20:46.234550", 
        "name": "studio-image"
      }
    ]
  }, 
  "type": "charm", 
  "id": "ydBmjPqafc9RoYcAttbzpqZXvMliaXn3", 
  "name": "finos-legend-studio-k8s"
}
```
